[programs.localnet]
escrow-anchor = "3kyu7viB2VYRVEm2B6xvZy2KvQAC7q9ZpbbzMGjnWJdo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/ppoliani/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
